version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/PayloadPro/svc.pro.payload.stats
    steps:
      - checkout
      - run: 
          name: go get
          command: go get -v -t -d ./...
      - run:
          name: test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: 
          name: go test
          command: |
            ./cc-test-reporter before-build
            go test -v -coverprofile=c.out ./...
            ./cc-test-reporter after-build --exit-code $?
